export enum ErrorsEnum {
  CAMERA_PERMISSION_DENIED = 'CAMERA_PERMISSION_DENIED',
  PHOTOS_PERMISSION_DENIED = 'PHOTOS_PERMISSION_DENIED',
  NO_FILE_SELECTED = 'NO_FILE_SELECTED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  UNKNOWN = 'UNKNOWN',
}
